from error.ErrnoError import ErrnoError
from error.InvalidStateError import InvalidStateError
from error.ArgumentError import ArgumentError
from error.IllegalOperationError import IllegalOperationError
from error.NotSupportedError import NotSupportedError